FROM golang:1.16.6-alpine AS dev
WORKDIR /go/src/app
COPY . .
RUN go mod download && go build -o main .

FROM alpine:latest AS deployment
COPY --from=builder /go/src/app/main .
ENTRYPOINT ["./main"]
CMD ["-u", "", "-p", "", "-w", ""]